chore: upgrade to Autofac v6
autofac/Autofac.Extras.CommonServiceLocator pull request #10
Opened 2020-10-03 09:00 UTC by alsami

* Upgrade packages
* Add TFM `netstandard2.0` & `netstandard2.1` to be aligned with `Autofac` target-frameworks
* Add some solution folders / items
* Cleanup / delete csproj meta-data

2020-10-04 17:48 UTC, tillig commented on appveyor.yml
> +version: 7.0.0.{build}
I think this file can be rolled back since we can stay compatible with 5.x.

2020-10-04 17:49 UTC, tillig requested changes
I think a couple of these can be rolled back and it'll be good. There may have been some overlap with @alistairjevans work.

2020-10-04 17:49 UTC, tillig commented on src/Autofac.Extras.CommonServiceLocator/Autofac.Extras.CommonServiceLocator.csproj
> +    <PackageReference Include="Autofac" Version="6.0.0" />
Looks like @alistairjevans was able to make this a range.

2020-10-04 17:57 UTC, alistairjevans commented
Oh, I'm sorry @alsami, I didn't see this incoming PR this morning; I just took @alexmg's changes and released the package!

2020-10-05 07:32 UTC, alexmg commented
There shouldn't be any problems with the released package as it stands. The only required change was extending the supported Autofac package range to `[5.0.0,7.0.0)`. That was the reason I only bumped the minor version to `6.0.1` for this package.

If we want to include the additional `netstandard2.1` target inlcuded in this PR we can release a `6.0.2` version. The Autofac package has included in the `netstandard2.1` target since `5.0.0`, though it may not be worth the effort just for that.

2020-10-05 07:39 UTC, alistairjevans commented
I'd agree that it may not be worth the additional effort to release another package version. But we can merge the `netstandard21` addition in and it can go out whenever the next release happens.

2020-10-05 16:18 UTC, alsami commented
No worries @alistairjevans was my bad actually. I considered the PR changes to be the release changes w/o you having it merged.

I will address the related comments latest tommorow.

2020-10-06 06:21 UTC, alsami commented
Changed back the version and made the compatibility of Autofac a range again.

2020-10-06 07:48 UTC, alistairjevans commented
@alsami, as per my comment on the v6 thread, can you take the `PublicSign` condition out of the project? This package still builds on Windows, but it makes me nervous that we'll forget in the future when we switch to Linux.

2020-10-06 08:16 UTC, alsami commented
Done

2020-10-06 16:20 UTC, alistairjevans commented
@tillig, just need you to press the right buttons on this one I think now.

2020-10-06 20:11 UTC, tillig approved these changes
🎉

2020-10-06 20:11 UTC, merged